from bitmovin.encoding.manifests.dash.periods.adaptationsets.representations.cmaf.contentprotection.contentprotection_api import ContentprotectionApi
from bitmovin.encoding.manifests.dash.periods.adaptationsets.representations.cmaf.contentprotection.content_protection_list_query_params import ContentProtectionListQueryParams
